local val = 0
local currOp = "add"
local ops = {
    inc = function(x) return x + val end,
    dec = function(x) return x - val end,
    mul = function(x) return x * val end,
    div = function(x) return x / val end
}
local OP = ops.inc
local noOp = {}

local function UNKNOWN(node)
    return "???"
end
local NONE
local function DRAW_LAYER(node)
    return ((node.flags >> 8) & 0xFF)
end
local function DRAW_LAYER_CAST(node)
    return DRAW_LAYER(node.node)
end
local function FROM_VEC3F(key)
    return function (node)
        local v = node[key]
        if v.x then v.x = OP(v.x) end
        if v.y then v.y = OP(v.y) end
        if v.z then v.z = OP(v.z) end
        return v.x..", "
             ..v.y..", "
             ..v.z
    end
end
local function FROM_VEC3S(key)
    return function (node)
        local v = node[key]
        if v.x then v.x = OP(v.x) end
        if v.y then v.y = OP(v.y) end
        if v.z then v.z = OP(v.z) end
        -- djui_chat_message_create(tostring(v._pointer)..":"..tostring(v._lot))
        return tonumber(string.format("%.0f", ((v.x or 0) * 180/32768)))..", "
             ..tonumber(string.format("%.0f", ((v.y or 0) * 180/32768)))..", "
             ..tonumber(string.format("%.0f", ((v.z or 0) * 180/32768)))
    end
end

local types = {
    [GRAPH_NODE_TYPE_ROOT                ] = { name = "NODE_SCREEN_AREA", fields = { "numEntries", "x", "y", "width", "height" } },
    [GRAPH_NODE_TYPE_ORTHO_PROJECTION    ] = { name = "NODE_ORTHO",       fields = { "scale" } },
    [GRAPH_NODE_TYPE_PERSPECTIVE         ] = { name = "CAMERA_FRUSTUM",   fields = { "fov", "near", "far" } },
    [GRAPH_NODE_TYPE_MASTER_LIST         ] = { name = "ZBUFFER",          fields = { function(node) return node.flags & GRAPH_RENDER_Z_BUFFER end } },
    [GRAPH_NODE_TYPE_START               ] = { name = "NODE_START",       fields = { NONE } },
    [GRAPH_NODE_TYPE_LEVEL_OF_DETAIL     ] = { name = "RENDER_RANGE",     fields = { "minDistance", "maxDistance" } },
    [GRAPH_NODE_TYPE_SWITCH_CASE         ] = { name = "SWITCH_CASE",      fields = { "parameter", UNKNOWN } },
    [GRAPH_NODE_TYPE_CAMERA              ] = { name = "CAMERA",           fields = { UNKNOWN, FROM_VEC3F("pos"), FROM_VEC3F("focus"), UNKNOWN } },
    [GRAPH_NODE_TYPE_TRANSLATION_ROTATION] = { name = "TRANSLATE_ROTATE", fields = { DRAW_LAYER_CAST, FROM_VEC3F("translation"), FROM_VEC3S("rotation") } },
    [GRAPH_NODE_TYPE_TRANSLATION         ] = { name = "TRANSLATE_NODE",   fields = { DRAW_LAYER_CAST, FROM_VEC3F("translation") } },
    [GRAPH_NODE_TYPE_ROTATION            ] = { name = "ROTATION_NODE",    fields = { DRAW_LAYER_CAST, FROM_VEC3S("rotation") } },
    [GRAPH_NODE_TYPE_OBJECT              ] = { name = "OBJECT",           fields = { NONE } }, -- is this even needed?
    [GRAPH_NODE_TYPE_ANIMATED_PART       ] = { name = "ANIMATED_PART",    fields = { DRAW_LAYER_CAST, FROM_VEC3F("translation"), "displayList" } },
    [GRAPH_NODE_TYPE_BILLBOARD           ] = { name = "BILLBOARD",        fields = { NONE } },
    [GRAPH_NODE_TYPE_DISPLAY_LIST        ] = { name = "DISPLAY_LIST",     fields = { DRAW_LAYER_CAST, "displayList" } },
    [GRAPH_NODE_TYPE_SCALE               ] = { name = "SCALE",            fields = { DRAW_LAYER_CAST, "scale" } },
    [GRAPH_NODE_TYPE_SHADOW              ] = { name = "SHADOW",           fields = { "shadowScale", "shadowSolidity", "shadowType" } },
    [GRAPH_NODE_TYPE_OBJECT_PARENT       ] = { name = "RENDER_OBJ",       fields = { NONE } }, -- is this even needed?
    [GRAPH_NODE_TYPE_GENERATED_LIST      ] = { name = "ASM",              fields = { "parameter", UNKNOWN } },
    [GRAPH_NODE_TYPE_BACKGROUND          ] = { name = "BACKGROUND",       fields = { "background", UNKNOWN  } },
    [GRAPH_NODE_TYPE_HELD_OBJ            ] = { name = "HELD_OBJECT",      fields = { "playerIndex", FROM_VEC3F("translation"), UNKNOWN } },
    [GRAPH_NODE_TYPE_CULLING_RADIUS      ] = { name = "CULLING_RADIUS",   fields = { "cullingRadius" } },
}

local hasDL = {
    [GRAPH_NODE_TYPE_ANIMATED_PART       ] = 1,
    [GRAPH_NODE_TYPE_DISPLAY_LIST        ] = 1,
    [GRAPH_NODE_TYPE_BILLBOARD           ] = 1,
    [GRAPH_NODE_TYPE_ROTATION            ] = 1,
    [GRAPH_NODE_TYPE_SCALE               ] = 1,
    [GRAPH_NODE_TYPE_TRANSLATION_ROTATION] = 1,
    [GRAPH_NODE_TYPE_TRANSLATION         ] = 1
}

local immutable = {
    ["parameter"] = 1,
    ["shadowScale"] = 1,
    ["shadowSolidity"] = 1,
    ["shadowType"] = 1,
    ["playerIndex"] = 1,
    ["scale"] = 1,
    ["displayList"] = 1
}

local real = djui_chat_message_create
local t = 0
local indent = ""
local e = false
djui_chat_message_create = function (msg)
    if e then
        real(indent..msg)
        print(indent..msg)
    end

    -- real(string.sub(indent..msg,17+4))
    -- print(string.sub(indent..msg,17+4))

    -- t = t + 1
    -- if t > 60 then return e..nil end
end

---@type GraphNode
local mnode

---@type Pointer_Gfx[]
local dls = {}

local currIndex
local animParts = {}
---@param m MarioState
hook_event(HOOK_MARIO_UPDATE, function (m)
    if m.playerIndex ~= 0 then return end
    if mnode ~= m.marioObj.header.gfx.sharedChild then
        djui_chat_message_create("new model!")
        mnode = m.marioObj.header.gfx.sharedChild

        currIndex = m.playerIndex
        animParts[currIndex] = {}
        dls = {}
        traverse_node(mnode)

        djui_chat_message_create("DisplayLists: "..#dls)
    end
end)

function traverse_children(node)
    ---@type GraphNode
    local child = node.children
    local firstChild = child
    if child then
        djui_chat_message_create("GEO_OPEN_NODE(),")
        indent = indent.."    "
    else return end
    local c = 1
    repeat
        local nodeType = types[child.type]
        local nodeCast = cast_graph_node(child)

        local s = "GEO_"..nodeType.name.."("
        for i, field in ipairs(nodeType.fields) do
            local value

            if type(field) == "function" then
                value = field(nodeCast)
            else value = nodeCast[field]
                if not noOp[nodeType.name] and not immutable[field] then
                    if nodeType.name and not immutable[field] then
                    djui_chat_message_create(""..nodeCast[field])
                    nodeCast[field] = OP(nodeCast[field])
                    djui_chat_message_create(""..nodeCast[field])
                    end
                end
            end

            s = s..(tostring(value) or "nil")
            if i ~= #nodeType.fields then
                s = s..", "
            end
        end
        s = s.."),"

        if hasDL[child.type] and nodeCast.displayList then
            table.insert(dls, nodeCast.displayList)
            -- s = s.." (HAS DISPLAY LIST, #"..#dls..")"
        end

        -- s = s.."                                                                                                                                                                                                                                                                                                                                    "
        -- s = s:sub(1, math.max(128-#indent, 0))
        -- s = s.." (child #"..c..", "..tostring(child._pointer)..":"..tostring(child._lot)..", "..tostring(nodeCast._pointer)..":"..tostring(nodeCast._lot)..")"

        -- for this mod
        if child.type == GRAPH_NODE_TYPE_ANIMATED_PART then
            table.insert(animParts[currIndex], nodeCast)
        end
        -- for this mod

        djui_chat_message_create(s)
        c = c + 1

        traverse_children(child)
        child = child.next
    until child == firstChild

    indent = indent:sub(5)
    djui_chat_message_create("GEO_CLOSE_NODE(),")
end

function traverse_node(node)
    djui_chat_message_create("GEO_"..types[node.type].name.."(),")
    traverse_children(node)
    djui_chat_message_create("GEO_END(),")
    val = 0
end

hook_chat_command("op", "set", function (msg)
    OP = ops[msg] or ops["add"]
    return true
end)
hook_chat_command("pop", "everything", function (msg)
    t = 0
    indent = ""
    val = tonumber(msg) or 0
    e = true
    traverse_node(mnode)
    e = false
    return true
end)

hook_chat_command("noop", "a type", function (msg)
    msg = msg:upper()
    local real
    for i, type in pairs(types) do
        if msg == type.name then
            real = 1
        end
    end
    if real then
        noOp[msg] = 1
    else djui_chat_message_create("doesn't exist!") end
    return true
end)

hook_chat_command("noop", "a type", function (msg)
    msg = msg:upper()
    noOp[msg] = nil
    return true
end)

local p = print
function print(...)
    -- if true then return end
    p(...)
end
local maxDLs = 5
local gdl = 0
local gvtxop = 0
local gvtx = 0
hook_chat_command("crumple", "the pumples", function (div)
    div = tonumber(div)
    if not div then return false end
    for i = 1, #dls do
        gdl = gdl + 1
        print("dl #"..i)
        gfx_parse(dls[i], function (dl, op)
            if op == G_VTX then
                gvtxop = gvtxop + 1
                print("G_VTX #"..gvtxop)

                local c = 0
                ---@type Vtx
                local vtx = vtx_get_vertex(gfx_get_vertex_buffer(dl), 0)
                repeat
                    vtx.x = ((vtx.x + div/2) // div) * div
                    vtx.y = ((vtx.y + div/2) // div) * div
                    vtx.z = ((vtx.z + div/2) // div) * div

                    c = c + 1
                    gvtx = gvtx + 1
                    vtx = vtx_get_next_vertex(vtx)
                until not vtx
            end
        end)
    end
    print("STOP!")
    print(gdl.." total display lists processed")
    print(gvtxop.." total vertex operations processed")
    print(gvtx.." total vertices processed")
    return true
end)

-- local textures = {
--     get_texture_info("amp_seg8_texture_08000F18"),
--     get_texture_info("amp_seg8_texture_08001318"),
--     get_texture_info("amp_seg8_texture_08001B18"),
--     get_texture_info("amp_seg8_texture_08002318"),
--     get_texture_info("blue_coin_switch_seg8_texture_08000018"),
--     get_texture_info("blue_coin_switch_seg8_texture_08000418"),
--     get_texture_info("blue_fish_seg3_texture_0301B5E0"),
--     get_texture_info("bobomb_seg8_texture_0801DA60"),
--     get_texture_info("bobomb_seg8_texture_0801EA60"),
--     get_texture_info("bobomb_seg8_texture_0801FA60"),
--     get_texture_info("bobomb_seg8_texture_08020A60"),
--     get_texture_info("bobomb_seg8_texture_08021A60"),
--     get_texture_info("bobomb_seg8_texture_08022260"),
--     get_texture_info("bomb_seg6_texture_06057AC0"),
--     get_texture_info("bomb_seg6_texture_06058AC0"),
--     get_texture_info("bomb_seg6_texture_06059AC0"),
--     get_texture_info("boo_seg5_texture_05009B40"),
--     get_texture_info("boo_seg5_texture_0500AB40"),
--     get_texture_info("boo_castle_seg6_texture_06015670"),
--     get_texture_info("boo_castle_seg6_texture_06016670"),
--     get_texture_info("book_seg5_texture_05002570"),
--     get_texture_info("bookend_seg5_texture_05000060"),
--     get_texture_info("bookend_seg5_texture_05000460"),
--     get_texture_info("bookend_seg5_texture_05000860"),
--     get_texture_info("bookend_seg5_texture_05000C60"),
--     get_texture_info("bookend_seg5_texture_05001060"),
--     get_texture_info("bowser_seg6_texture_0601F438"),
--     get_texture_info("bowser_seg6_texture_0601FC38"),
--     get_texture_info("bowser_seg6_texture_06020C38"),
--     get_texture_info("bowser_seg6_texture_06021438"),
--     get_texture_info("bowser_seg6_texture_06022438"),
--     get_texture_info("bowser_seg6_texture_06022C38"),
--     get_texture_info("bowser_seg6_texture_06023C38"),
--     get_texture_info("bowser_seg6_texture_06024438"),
--     get_texture_info("bowser_seg6_texture_06025438"),
--     get_texture_info("bowser_seg6_texture_06025C38"),
--     get_texture_info("bowser_seg6_texture_06026438"),
--     get_texture_info("bowser_seg6_texture_06027438"),
--     get_texture_info("bowser_seg6_texture_06028438"),
--     get_texture_info("bowser_seg6_texture_06028C38"),
--     get_texture_info("bowser_seg6_texture_06029C38"),
--     get_texture_info("bowser_seg6_texture_0602AC38"),
--     get_texture_info("bowser_seg6_texture_0602BC38"),
--     get_texture_info("bowser_seg6_texture_0602CC38"),
--     get_texture_info("bowser_seg6_texture_0602DC38"),
--     get_texture_info("bowser_seg6_texture_0602EC38"),
--     get_texture_info("bowser_seg6_texture_0602FC38"),
--     get_texture_info("bowser_seg6_texture_06030C38"),
--     get_texture_info("bowser_seg6_texture_06031C38"),
--     get_texture_info("bowser_seg6_texture_06032C38"),
--     get_texture_info("bowser_seg6_texture_06033C38"),
--     get_texture_info("bowser_seg6_texture_06034C38"),
--     get_texture_info("bowser_seg6_texture_06035C38"),
--     get_texture_info("bowser_seg6_texture_06036C38"),
--     get_texture_info("bowser_seg6_texture_06037C38"),
--     get_texture_info("flame_seg6_texture_06000000"),
--     get_texture_info("flame_seg6_texture_06002000"),
--     get_texture_info("flame_seg6_texture_06004000"),
--     get_texture_info("flame_seg6_texture_06006000"),
--     get_texture_info("flame_seg6_texture_06008000"),
--     get_texture_info("flame_seg6_texture_0600A000"),
--     get_texture_info("flame_seg6_texture_0600C000"),
--     get_texture_info("flame_seg6_texture_0600E000"),
--     get_texture_info("flame_seg6_texture_06010000"),
--     get_texture_info("flame_seg6_texture_06012000"),
--     get_texture_info("flame_seg6_texture_06014000"),
--     get_texture_info("flame_seg6_texture_06016000"),
--     get_texture_info("flame_seg6_texture_06018000"),
--     get_texture_info("flame_seg6_texture_0601A000"),
--     get_texture_info("bowser_key_left_texture"),
--     get_texture_info("bowser_key_right_texture"),
--     get_texture_info("breakable_box_seg8_texture_08011A90"),
--     get_texture_info("breakable_box_seg8_texture_08012290"),
--     get_texture_info("bub_seg6_texture_0600E2A8"),
--     get_texture_info("bub_seg6_texture_0600EAA8"),
--     get_texture_info("bub_seg6_texture_0600F2A8"),
--     get_texture_info("bub_seg6_texture_060102A8"),
--     get_texture_info("bubba_seg5_texture_05000008"),
--     get_texture_info("bubba_seg5_texture_05000408"),
--     get_texture_info("bubba_seg5_texture_05001408"),
--     get_texture_info("bubba_seg5_texture_05001C08"),
--     get_texture_info("bubba_seg5_texture_05002408"),
--     get_texture_info("bubble_seg4_texture_0401CD60"),
--     get_texture_info("bubble_seg4_texture_0401D560"),
--     get_texture_info("bullet_bill_seg5_texture_0500BAA8"),
--     get_texture_info("bullet_bill_seg5_texture_0500CAA8"),
--     get_texture_info("bully_seg5_texture_050000E0"),
--     get_texture_info("bully_seg5_texture_05000468"),
--     get_texture_info("bully_seg5_texture_05001468"),
--     get_texture_info("bully_seg5_texture_05002468"),
--     get_texture_info("burn_smoke_seg4_texture_04021800"),
--     get_texture_info("butterfly_seg3_texture_030043A8"),
--     get_texture_info("cannon_barrel_seg8_texture_080058A8"),
--     get_texture_info("cannon_base_seg8_texture_080049B8"),
--     get_texture_info("cannon_lid_seg8_texture_08004058"),
--     get_texture_info("capswitch_seg5_texture_05001C48"),
--     get_texture_info("capswitch_seg5_texture_05002C48"),
--     get_texture_info("chain_ball_seg6_texture_06020AE8"),
--     get_texture_info("chain_chomp_seg6_texture_060213D0"),
--     get_texture_info("chain_chomp_seg6_texture_06021BD0"),
--     get_texture_info("chain_chomp_seg6_texture_060223D0"),
--     get_texture_info("chain_chomp_seg6_texture_06022BD0"),
--     get_texture_info("chain_chomp_seg6_texture_060233D0"),
--     get_texture_info("chair_seg5_texture_05003060"),
--     get_texture_info("chair_seg5_texture_05003860"),
--     get_texture_info("chair_seg5_texture_05004060"),
--     get_texture_info("chair_seg5_texture_05004460"),
--     get_texture_info("checkerboard_platform_seg8_texture_0800C840"),
--     get_texture_info("checkerboard_platform_seg8_texture_0800CC40"),
--     get_texture_info("chilly_chief_seg6_texture_06000060"),
--     get_texture_info("chilly_chief_seg6_texture_06001060"),
--     get_texture_info("chilly_chief_seg6_texture_06002060"),
--     get_texture_info("chuckya_seg8_texture_08006778"),
--     get_texture_info("chuckya_seg8_texture_08007778"),
--     get_texture_info("chuckya_seg8_texture_08007F78"),
--     get_texture_info("chuckya_seg8_texture_08008F78"),
--     get_texture_info("clam_shell_seg5_texture_05000030"),
--     get_texture_info("clam_shell_seg5_texture_05000830"),
--     get_texture_info("coin_seg3_texture_03005780"),
--     get_texture_info("coin_seg3_texture_03005F80"),
--     get_texture_info("coin_seg3_texture_03006780"),
--     get_texture_info("coin_seg3_texture_03006F80"),
--     get_texture_info("cyan_fish_seg6_texture_0600D468"),
--     get_texture_info("dirt_seg3_texture_0302BDF8"),
--     get_texture_info("door_seg3_texture_03009D10"),
--     get_texture_info("door_seg3_texture_0300AD10"),
--     get_texture_info("door_seg3_texture_0300BD10"),
--     get_texture_info("door_seg3_texture_0300CD10"),
--     get_texture_info("door_seg3_texture_0300D510"),
--     get_texture_info("door_seg3_texture_0300E510"),
--     get_texture_info("door_seg3_texture_0300ED10"),
--     get_texture_info("door_seg3_texture_0300FD10"),
--     get_texture_info("door_seg3_texture_03010510"),
--     get_texture_info("door_seg3_texture_03011510"),
--     get_texture_info("door_seg3_texture_03011D10"),
--     get_texture_info("door_seg3_texture_03012510"),
--     get_texture_info("door_seg3_texture_03012D10"),
--     get_texture_info("door_seg3_texture_03013510"),
--     get_texture_info("dorrie_seg6_texture_06009BA0"),
--     get_texture_info("dorrie_seg6_texture_06009DA0"),
--     get_texture_info("dorrie_seg6_texture_0600ADA0"),
--     get_texture_info("exclamation_box_seg8_texture_08012E28"),
--     get_texture_info("exclamation_box_seg8_texture_08013628"),
--     get_texture_info("exclamation_box_seg8_texture_08014628"),
--     get_texture_info("exclamation_box_seg8_texture_08014E28"),
--     get_texture_info("exclamation_box_seg8_texture_08015E28"),
--     get_texture_info("exclamation_box_seg8_texture_08016628"),
--     get_texture_info("exclamation_box_seg8_texture_08017628"),
--     get_texture_info("exclamation_box_seg8_texture_08017E28"),
--     get_texture_info("exclamation_box_outline_seg8_texture_08025168"),
--     get_texture_info("exclamation_box_outline_seg8_texture_08025A80"),
--     get_texture_info("explosion_seg3_texture_03000A08"),
--     get_texture_info("explosion_seg3_texture_03001208"),
--     get_texture_info("explosion_seg3_texture_03001A08"),
--     get_texture_info("explosion_seg3_texture_03002208"),
--     get_texture_info("explosion_seg3_texture_03002A08"),
--     get_texture_info("explosion_seg3_texture_03003208"),
--     get_texture_info("explosion_seg3_texture_03003A08"),
--     get_texture_info("eyerok_seg5_texture_05008D40"),
--     get_texture_info("eyerok_seg5_texture_05009540"),
--     get_texture_info("eyerok_seg5_texture_05009D40"),
--     get_texture_info("eyerok_seg5_texture_0500A540"),
--     get_texture_info("eyerok_seg5_texture_0500AD40"),
--     get_texture_info("flame_seg3_texture_03017320"),
--     get_texture_info("flame_seg3_texture_03017B20"),
--     get_texture_info("flame_seg3_texture_03018320"),
--     get_texture_info("flame_seg3_texture_03018B20"),
--     get_texture_info("flame_seg3_texture_03019320"),
--     get_texture_info("flame_seg3_texture_03019B20"),
--     get_texture_info("flame_seg3_texture_0301A320"),
--     get_texture_info("flame_seg3_texture_0301AB20"),
--     get_texture_info("flyguy_seg8_texture_0800E088"),
--     get_texture_info("flyguy_seg8_texture_0800F088"),
--     get_texture_info("flyguy_seg8_texture_0800F888"),
--     get_texture_info("fwoosh_seg5_texture_05015808"),
--     get_texture_info("goomba_seg8_texture_08019530"),
--     get_texture_info("goomba_seg8_texture_08019D30"),
--     get_texture_info("goomba_seg8_texture_0801A530"),
--     get_texture_info("haunted_cage_seg5_texture_0500C288"),
--     get_texture_info("haunted_cage_seg5_texture_0500CA88"),
--     get_texture_info("haunted_cage_seg5_texture_0500D288"),
--     get_texture_info("haunted_cage_seg5_texture_0500D688"),
--     get_texture_info("haunted_cage_seg5_texture_0500DA88"),
--     get_texture_info("haunted_cage_seg5_texture_0500E288"),
--     get_texture_info("heart_seg8_texture_0800D7E0"),
--     get_texture_info("heave_ho_seg5_texture_0500E9C8"),
--     get_texture_info("heave_ho_seg5_texture_0500F1C8"),
--     get_texture_info("heave_ho_seg5_texture_0500F9C8"),
--     get_texture_info("heave_ho_seg5_texture_050109C8"),
--     get_texture_info("heave_ho_seg5_texture_050111C8"),
--     get_texture_info("heave_ho_seg5_texture_050113C8"),
--     get_texture_info("hoot_seg5_texture_05000A20"),
--     get_texture_info("hoot_seg5_texture_05001E50"),
--     get_texture_info("hoot_seg5_texture_05002650"),
--     get_texture_info("impact_ring_seg6_texture_0601CA50"),
--     get_texture_info("impact_ring_seg6_texture_0601DA50"),
--     get_texture_info("king_bobomb_seg5_texture_05000078"),
--     get_texture_info("king_bobomb_seg5_texture_05001078"),
--     get_texture_info("king_bobomb_seg5_texture_05002078"),
--     get_texture_info("king_bobomb_seg5_texture_05002878"),
--     get_texture_info("king_bobomb_seg5_texture_05004878"),
--     get_texture_info("king_bobomb_seg5_texture_05005878"),
--     get_texture_info("king_bobomb_seg5_texture_05006078"),
--     get_texture_info("king_bobomb_seg5_texture_05006478"),
--     get_texture_info("king_bobomb_seg5_texture_05008478"),
--     get_texture_info("king_bobomb_seg5_texture_05009478"),
--     get_texture_info("klepto_seg5_texture_05000008"),
--     get_texture_info("klepto_seg5_texture_05000808"),
--     get_texture_info("klepto_seg5_texture_05001008"),
--     get_texture_info("klepto_seg5_texture_05002008"),
--     get_texture_info("klepto_seg5_texture_05003008"),
--     get_texture_info("koopa_seg6_texture_06002648"),
--     get_texture_info("koopa_seg6_texture_06002E48"),
--     get_texture_info("koopa_seg6_texture_06003648"),
--     get_texture_info("koopa_seg6_texture_06003E48"),
--     get_texture_info("koopa_seg6_texture_06004648"),
--     get_texture_info("koopa_seg6_texture_06004E48"),
--     get_texture_info("koopa_seg6_texture_06005648"),
--     get_texture_info("koopa_seg6_texture_06005E48"),
--     get_texture_info("koopa_flag_seg6_texture_06000048"),
--     get_texture_info("koopa_shell_seg8_texture_080274A0"),
--     get_texture_info("koopa_shell_seg8_texture_08027CA0"),
--     get_texture_info("lakitu_seg6_texture_06000000"),
--     get_texture_info("lakitu_seg6_texture_06000800"),
--     get_texture_info("lakitu_seg6_texture_06001800"),
--     get_texture_info("lakitu_seg6_texture_06002800"),
--     get_texture_info("lakitu_seg6_texture_06003000"),
--     get_texture_info("lakitu_seg6_texture_06003800"),
--     get_texture_info("lakitu_enemy_seg5_texture_0500ECE0"),
--     get_texture_info("lakitu_enemy_seg5_texture_0500F4E0"),
--     get_texture_info("lakitu_enemy_seg5_texture_050104E0"),
--     get_texture_info("lakitu_enemy_seg5_texture_050114E0"),
--     get_texture_info("lakitu_enemy_seg5_texture_05011CE0"),
--     get_texture_info("leaves_seg3_texture_0301CBE0"),
--     get_texture_info("mad_piano_seg5_texture_05006AF0"),
--     get_texture_info("mad_piano_seg5_texture_050072F0"),
--     get_texture_info("mad_piano_seg5_texture_050076F0"),
--     get_texture_info("mad_piano_seg5_texture_05007AF0"),
--     get_texture_info("mad_piano_seg5_texture_05007EF0"),
--     get_texture_info("mad_piano_seg5_texture_050082F0"),
--     get_texture_info("manta_seg5_texture_050017A0"),
--     get_texture_info("manta_seg5_texture_05001FA0"),
--     get_texture_info("manta_seg5_texture_05002FA0"),
--     get_texture_info("manta_seg5_texture_050037A0"),
--     get_texture_info("metal_box_seg8_texture_08023998"),
--     get_texture_info("mips_seg6_texture_0600FB80"),
--     get_texture_info("mist_seg3_texture_03000080"),
--     get_texture_info("moneybag_seg6_texture_060039B0"),
--     get_texture_info("moneybag_seg6_texture_060049B0"),
--     get_texture_info("monty_mole_seg5_texture_05000970"),
--     get_texture_info("monty_mole_seg5_texture_05001170"),
--     get_texture_info("monty_mole_seg5_texture_05001970"),
--     get_texture_info("monty_mole_seg5_texture_05002170"),
--     get_texture_info("monty_mole_seg5_texture_05002970"),
--     get_texture_info("monty_mole_hole_seg5_texture_05000040"),
--     get_texture_info("mr_i_eyeball_seg6_texture_06000080"),
--     get_texture_info("mr_i_eyeball_seg6_texture_06001080"),
--     get_texture_info("mr_i_iris_seg6_texture_06002170"),
--     get_texture_info("mr_i_iris_seg6_texture_06002970"),
--     get_texture_info("mr_i_iris_seg6_texture_06003170"),
--     get_texture_info("mr_i_iris_seg6_texture_06003970"),
--     get_texture_info("mushroom_1up_seg3_texture_03029628"),
--     get_texture_info("peach_seg5_texture_05000A28"),
--     get_texture_info("peach_seg5_texture_05001228"),
--     get_texture_info("peach_seg5_texture_05001A28"),
--     get_texture_info("peach_seg5_texture_05002228"),
--     get_texture_info("peach_seg5_texture_05002A28"),
--     get_texture_info("peach_seg5_texture_05002C28"),
--     get_texture_info("peach_seg5_texture_05002E28"),
--     get_texture_info("peach_seg5_texture_05003628"),
--     get_texture_info("peach_seg5_texture_05003E28"),
--     get_texture_info("peach_seg5_texture_05004028"),
--     get_texture_info("pebble_seg3_texture_0301C300"),
--     get_texture_info("penguin_seg5_texture_05002DE0"),
--     get_texture_info("penguin_seg5_texture_050035E0"),
--     get_texture_info("penguin_seg5_texture_05003DE0"),
--     get_texture_info("penguin_seg5_texture_050045E0"),
--     get_texture_info("penguin_seg5_texture_05004DE0"),
--     get_texture_info("penguin_seg5_texture_050055E0"),
--     get_texture_info("piranha_plant_seg6_texture_060113F8"),
--     get_texture_info("piranha_plant_seg6_texture_060123F8"),
--     get_texture_info("piranha_plant_seg6_texture_06012BF8"),
--     get_texture_info("piranha_plant_seg6_texture_060133F8"),
--     get_texture_info("piranha_plant_seg6_texture_06013BF8"),
--     get_texture_info("piranha_plant_seg6_texture_060143F8"),
--     get_texture_info("pokey_seg5_texture_05011750"),
--     get_texture_info("pokey_seg5_texture_05011F50"),
--     get_texture_info("pokey_seg5_texture_05012878"),
--     get_texture_info("poundable_pole_seg6_texture_06001050"),
--     get_texture_info("poundable_pole_seg6_texture_06001850"),
--     get_texture_info("texture_power_meter_left_side"),
--     get_texture_info("texture_power_meter_right_side"),
--     get_texture_info("texture_power_meter_full"),
--     get_texture_info("texture_power_meter_seven_segments"),
--     get_texture_info("texture_power_meter_six_segments"),
--     get_texture_info("texture_power_meter_five_segments"),
--     get_texture_info("texture_power_meter_four_segments"),
--     get_texture_info("texture_power_meter_three_segments"),
--     get_texture_info("texture_power_meter_two_segments"),
--     get_texture_info("texture_power_meter_one_segments"),
--     get_texture_info("purple_switch_seg8_texture_0800C0A8"),
--     get_texture_info("purple_switch_seg8_texture_0800C128"),
--     get_texture_info("sand_seg3_texture_0302BAD0"),
--     get_texture_info("scuttlebug_seg6_texture_06010108"),
--     get_texture_info("scuttlebug_seg6_texture_06010908"),
--     get_texture_info("scuttlebug_seg6_texture_06011908"),
--     get_texture_info("scuttlebug_seg6_texture_06012908"),
--     get_texture_info("scuttlebug_seg6_texture_06013108"),
--     get_texture_info("seaweed_seg6_texture_06007E10"),
--     get_texture_info("seaweed_seg6_texture_06008610"),
--     get_texture_info("seaweed_seg6_texture_06008E10"),
--     get_texture_info("seaweed_seg6_texture_06009610"),
--     get_texture_info("skeeter_seg6_texture_06000090"),
--     get_texture_info("skeeter_seg6_texture_06000890"),
--     get_texture_info("smoke_seg5_texture_050072C0"),
--     get_texture_info("snowman_seg5_texture_05008C70"),
--     get_texture_info("snowman_seg5_texture_05009470"),
--     get_texture_info("snowman_seg5_texture_0500A470"),
--     get_texture_info("snowman_seg5_texture_0500B470"),
--     get_texture_info("snowman_seg5_texture_0500BC70"),
--     get_texture_info("snufit_seg6_texture_060070E0"),
--     get_texture_info("snufit_seg6_texture_060078E0"),
--     get_texture_info("snufit_seg6_texture_060080E0"),
--     get_texture_info("snufit_seg6_texture_060084E0"),
--     get_texture_info("sparkles_seg4_texture_04027490"),
--     get_texture_info("sparkles_seg4_texture_04027C90"),
--     get_texture_info("sparkles_seg4_texture_04028490"),
--     get_texture_info("sparkles_seg4_texture_04028C90"),
--     get_texture_info("sparkles_seg4_texture_04029490"),
--     get_texture_info("sparkles_seg4_texture_04029C90"),
--     get_texture_info("sparkles_animation_seg4_texture_04032A88"),
--     get_texture_info("sparkles_animation_seg4_texture_04033288"),
--     get_texture_info("sparkles_animation_seg4_texture_04033A88"),
--     get_texture_info("sparkles_animation_seg4_texture_04034288"),
--     get_texture_info("sparkles_animation_seg4_texture_04034A88"),
--     get_texture_info("spindrift_seg5_texture_050006D0"),
--     get_texture_info("spindrift_seg5_texture_05000ED0"),
--     get_texture_info("spindrift_seg5_texture_050016D0"),
--     get_texture_info("spindrift_seg5_texture_05001ED0"),
--     get_texture_info("springboard_seg5_texture_05000018"),
--     get_texture_info("springboard_seg5_texture_05000818"),
--     get_texture_info("star_seg3_texture_0302A6F0"),
--     get_texture_info("star_seg3_texture_0302AEF0"),
--     get_texture_info("stomp_smoke_seg4_texture_04022148"),
--     get_texture_info("stomp_smoke_seg4_texture_04022948"),
--     get_texture_info("stomp_smoke_seg4_texture_04023148"),
--     get_texture_info("stomp_smoke_seg4_texture_04023948"),
--     get_texture_info("stomp_smoke_seg4_texture_04024148"),
--     get_texture_info("stomp_smoke_seg4_texture_04024948"),
--     get_texture_info("sushi_seg5_texture_05008ED0"),
--     get_texture_info("sushi_seg5_texture_050096D0"),
--     get_texture_info("sushi_seg5_texture_05009AD0"),
--     get_texture_info("swoop_seg6_texture_06004270"),
--     get_texture_info("swoop_seg6_texture_06004A70"),
--     get_texture_info("swoop_seg6_texture_06005270"),
--     get_texture_info("swoop_seg6_texture_06005A70"),
--     get_texture_info("thwomp_seg5_texture_05009900"),
--     get_texture_info("thwomp_seg5_texture_0500A900"),
--     get_texture_info("toad_seg6_texture_06005920"),
--     get_texture_info("toad_seg6_texture_06006120"),
--     get_texture_info("tornado_seg5_texture_05013128"),
--     get_texture_info("treasure_chest_seg6_texture_06013FA8"),
--     get_texture_info("treasure_chest_seg6_texture_060147A8"),
--     get_texture_info("treasure_chest_seg6_texture_06014FA8"),
--     get_texture_info("treasure_chest_seg6_texture_060157A8"),
--     get_texture_info("tree_seg3_texture_0302DE28"),
--     get_texture_info("tree_seg3_texture_0302EE28"),
--     get_texture_info("tree_seg3_texture_0302FF60"),
--     get_texture_info("tree_seg3_texture_03031048"),
--     get_texture_info("tree_seg3_texture_03032218"),
--     get_texture_info("ukiki_seg5_texture_05007BC0"),
--     get_texture_info("ukiki_seg5_texture_05008BC0"),
--     get_texture_info("ukiki_seg5_texture_05009BC0"),
--     get_texture_info("ukiki_seg5_texture_0500A3C0"),
--     get_texture_info("unagi_seg5_texture_0500AF20"),
--     get_texture_info("unagi_seg5_texture_0500B720"),
--     get_texture_info("unagi_seg5_texture_0500B920"),
--     get_texture_info("unagi_seg5_texture_0500C120"),
--     get_texture_info("unagi_seg5_texture_0500C320"),
--     get_texture_info("unagi_seg5_texture_0500C3A0"),
--     get_texture_info("smoke_seg4_texture_0401DEA0"),
--     get_texture_info("smoke_seg4_texture_0401E6A0"),
--     get_texture_info("smoke_seg4_texture_0401EEA0"),
--     get_texture_info("smoke_seg4_texture_0401F6A0"),
--     get_texture_info("smoke_seg4_texture_0401FEA0"),
--     get_texture_info("smoke_seg4_texture_040206A0"),
--     get_texture_info("smoke_seg4_texture_04020EA0"),
--     get_texture_info("warp_pipe_seg3_texture_03007E40"),
--     get_texture_info("warp_pipe_seg3_texture_03009168"),
--     get_texture_info("water_bubble_seg5_texture_0500FE80"),
--     get_texture_info("water_mine_seg6_texture_0600A4F8"),
--     get_texture_info("water_mine_seg6_texture_0600B4F8"),
--     get_texture_info("water_mine_seg6_texture_0600C4F8"),
--     get_texture_info("water_ring_seg6_texture_06012380"),
--     get_texture_info("water_splash_seg4_texture_0402A5C8"),
--     get_texture_info("water_splash_seg4_texture_0402B5C8"),
--     get_texture_info("water_splash_seg4_texture_0402C5C8"),
--     get_texture_info("water_splash_seg4_texture_0402D5C8"),
--     get_texture_info("water_splash_seg4_texture_0402E5C8"),
--     get_texture_info("water_splash_seg4_texture_0402F5C8"),
--     get_texture_info("water_splash_seg4_texture_040305C8"),
--     get_texture_info("water_splash_seg4_texture_040315C8"),
--     get_texture_info("water_wave_seg4_texture_04025358"),
--     get_texture_info("water_wave_seg4_texture_04025B58"),
--     get_texture_info("water_wave_seg4_texture_04026358"),
--     get_texture_info("water_wave_seg4_texture_04026B58"),
--     get_texture_info("whirlpool_seg5_texture_05012848"),
--     get_texture_info("white_particle_texture"),
--     get_texture_info("white_particle_small_texture"),
--     get_texture_info("whomp_seg6_texture_0601C360"),
--     get_texture_info("whomp_seg6_texture_0601D360"),
--     get_texture_info("whomp_seg6_texture_0601E360"),
--     get_texture_info("whomp_seg6_texture_0601EB60"),
--     get_texture_info("wiggler_seg5_texture_05005A30"),
--     get_texture_info("wiggler_seg5_texture_05006A30"),
--     get_texture_info("wiggler_seg5_texture_05007A30"),
--     get_texture_info("wiggler_seg5_texture_05008230"),
--     get_texture_info("wiggler_seg5_texture_05008A30"),
--     get_texture_info("wiggler_seg5_texture_05009230"),
--     get_texture_info("wiggler_seg5_texture_0500A230"),
--     get_texture_info("wooden_signpost_seg3_texture_0302C9C8"),
--     get_texture_info("wooden_signpost_seg3_texture_0302D1C8"),
--     get_texture_info("yellow_sphere_seg6_texture_0601EB88"),
--     get_texture_info("yellow_sphere_seg5_texture_05000040"),
--     get_texture_info("yoshi_seg5_texture_0501C4A0"),
--     get_texture_info("yoshi_seg5_texture_0501C6A0"),
--     get_texture_info("yoshi_seg5_texture_0501C8A0"),
--     get_texture_info("yoshi_egg_seg5_texture_050057B8"),
--     get_texture_info("yoshi_egg_seg5_texture_05005FB8"),
--     get_texture_info("yoshi_egg_seg5_texture_050067B8"),
--     get_texture_info("yoshi_egg_seg5_texture_05006FB8"),
--     get_texture_info("yoshi_egg_seg5_texture_050077B8"),
--     get_texture_info("yoshi_egg_seg5_texture_05007FB8"),
--     get_texture_info("yoshi_egg_seg5_texture_050087B8"),
--     get_texture_info("yoshi_egg_seg5_texture_05008FB8"),
--     get_texture_info("cave_09000000"),
--     get_texture_info("cave_09001000"),
--     get_texture_info("cave_09001800"),
--     get_texture_info("cave_09002800"),
--     get_texture_info("cave_09003000"),
--     get_texture_info("cave_09003800"),
--     get_texture_info("cave_09004800"),
--     get_texture_info("cave_09005800"),
--     get_texture_info("cave_09006800"),
--     get_texture_info("cave_09007000"),
--     get_texture_info("cave_09007800"),
--     get_texture_info("cave_09008800"),
--     get_texture_info("cave_09009800"),
--     get_texture_info("cave_0900A000"),
--     get_texture_info("cave_0900A800"),
--     get_texture_info("cave_0900B800"),
--     get_texture_info("cave_0900C000"),
--     get_texture_info("effect_0B000008"),
--     get_texture_info("effect_0B000808"),
--     get_texture_info("effect_0B001008"),
--     get_texture_info("effect_0B001808"),
--     get_texture_info("effect_0B002020"),
--     get_texture_info("effect_0B002820"),
--     get_texture_info("effect_0B003020"),
--     get_texture_info("effect_0B003820"),
--     get_texture_info("effect_0B004020"),
--     get_texture_info("effect_0B004820"),
--     get_texture_info("effect_0B005020"),
--     get_texture_info("effect_0B005820"),
--     get_texture_info("effect_0B006048"),
--     get_texture_info("effect_0B00684C"),
--     get_texture_info("effect_0B006AD8"),
--     get_texture_info("fire_09000000"),
--     get_texture_info("fire_09000800"),
--     get_texture_info("fire_09001000"),
--     get_texture_info("fire_09001800"),
--     get_texture_info("fire_09002000"),
--     get_texture_info("fire_09002800"),
--     get_texture_info("fire_09003000"),
--     get_texture_info("fire_09003800"),
--     get_texture_info("fire_09004000"),
--     get_texture_info("fire_09004800"),
--     get_texture_info("fire_09005000"),
--     get_texture_info("fire_09005800"),
--     get_texture_info("fire_09006000"),
--     get_texture_info("fire_09006800"),
--     get_texture_info("fire_09007000"),
--     get_texture_info("fire_09007800"),
--     get_texture_info("fire_09008000"),
--     get_texture_info("fire_09008800"),
--     get_texture_info("fire_09009000"),
--     get_texture_info("fire_09009800"),
--     get_texture_info("fire_0900A000"),
--     get_texture_info("fire_0900A800"),
--     get_texture_info("fire_0900B000"),
--     get_texture_info("fire_0900B800"),
--     get_texture_info("generic_09000000"),
--     get_texture_info("generic_09000800"),
--     get_texture_info("generic_09001000"),
--     get_texture_info("generic_09001800"),
--     get_texture_info("generic_09002000"),
--     get_texture_info("generic_09002800"),
--     get_texture_info("generic_09003000"),
--     get_texture_info("generic_09003800"),
--     get_texture_info("generic_09004000"),
--     get_texture_info("generic_09004800"),
--     get_texture_info("generic_09005000"),
--     get_texture_info("generic_09005800"),
--     get_texture_info("generic_09006000"),
--     get_texture_info("generic_09007000"),
--     get_texture_info("generic_09007800"),
--     get_texture_info("generic_09008000"),
--     get_texture_info("generic_09008800"),
--     get_texture_info("generic_09009000"),
--     get_texture_info("generic_09009800"),
--     get_texture_info("generic_0900A000"),
--     get_texture_info("generic_0900A800"),
--     get_texture_info("generic_0900B000"),
--     get_texture_info("grass_09000000"),
--     get_texture_info("grass_09000800"),
--     get_texture_info("grass_09001000"),
--     get_texture_info("grass_09001800"),
--     get_texture_info("grass_09002000"),
--     get_texture_info("grass_09002800"),
--     get_texture_info("grass_09003000"),
--     get_texture_info("grass_09003800"),
--     get_texture_info("grass_09004000"),
--     get_texture_info("grass_09004800"),
--     get_texture_info("grass_09005000"),
--     get_texture_info("grass_09005800"),
--     get_texture_info("grass_09006000"),
--     get_texture_info("grass_09006800"),
--     get_texture_info("grass_09007000"),
--     get_texture_info("grass_09007800"),
--     get_texture_info("grass_09008000"),
--     get_texture_info("grass_09008800"),
--     get_texture_info("grass_09009000"),
--     get_texture_info("grass_09009800"),
--     get_texture_info("grass_0900A000"),
--     get_texture_info("grass_0900A800"),
--     get_texture_info("grass_0900B000"),
--     get_texture_info("grass_0900B800"),
--     get_texture_info("inside_09000000"),
--     get_texture_info("inside_09001000"),
--     get_texture_info("inside_09002000"),
--     get_texture_info("inside_09003000"),
--     get_texture_info("inside_09003800"),
--     get_texture_info("inside_09004000"),
--     get_texture_info("inside_09004800"),
--     get_texture_info("inside_09005000"),
--     get_texture_info("inside_09005800"),
--     get_texture_info("inside_09006000"),
--     get_texture_info("inside_09007000"),
--     get_texture_info("inside_09008000"),
--     get_texture_info("inside_09008800"),
--     get_texture_info("inside_09009000"),
--     get_texture_info("inside_0900A000"),
--     get_texture_info("inside_0900B000"),
--     get_texture_info("inside_0900B800"),
--     get_texture_info("machine_09000000"),
--     get_texture_info("machine_09000800"),
--     get_texture_info("machine_09001000"),
--     get_texture_info("machine_09001800"),
--     get_texture_info("machine_09002000"),
--     get_texture_info("machine_09002800"),
--     get_texture_info("machine_09003000"),
--     get_texture_info("machine_09003800"),
--     get_texture_info("machine_09004000"),
--     get_texture_info("machine_09005000"),
--     get_texture_info("machine_09005800"),
--     get_texture_info("machine_09006000"),
--     get_texture_info("machine_09006800"),
--     get_texture_info("machine_09007000"),
--     get_texture_info("machine_09007800"),
--     get_texture_info("machine_09008000"),
--     get_texture_info("machine_09008400"),
--     get_texture_info("mountain_09000000"),
--     get_texture_info("mountain_09000800"),
--     get_texture_info("mountain_09001800"),
--     get_texture_info("mountain_09002800"),
--     get_texture_info("mountain_09003000"),
--     get_texture_info("mountain_09003800"),
--     get_texture_info("mountain_09004000"),
--     get_texture_info("mountain_09004800"),
--     get_texture_info("mountain_09005000"),
--     get_texture_info("mountain_09005800"),
--     get_texture_info("mountain_09006800"),
--     get_texture_info("mountain_09007000"),
--     get_texture_info("mountain_09007800"),
--     get_texture_info("mountain_09008000"),
--     get_texture_info("mountain_09008800"),
--     get_texture_info("mountain_09009800"),
--     get_texture_info("mountain_0900A000"),
--     get_texture_info("mountain_0900A800"),
--     get_texture_info("mountain_0900B000"),
--     get_texture_info("mountain_0900B800"),
--     get_texture_info("mountain_0900C000"),
--     get_texture_info("outside_09000000"),
--     get_texture_info("outside_09000800"),
--     get_texture_info("outside_09001000"),
--     get_texture_info("outside_09002000"),
--     get_texture_info("outside_09003000"),
--     get_texture_info("outside_09003800"),
--     get_texture_info("outside_09004000"),
--     get_texture_info("outside_09004800"),
--     get_texture_info("outside_09005800"),
--     get_texture_info("outside_09006000"),
--     get_texture_info("outside_09006800"),
--     get_texture_info("outside_09007800"),
--     get_texture_info("outside_09008000"),
--     get_texture_info("outside_09008800"),
--     get_texture_info("outside_09009000"),
--     get_texture_info("outside_09009800"),
--     get_texture_info("outside_0900A000"),
--     get_texture_info("outside_0900A800"),
--     get_texture_info("outside_0900B000"),
--     get_texture_info("outside_0900B400"),
--     get_texture_info("outside_0900BC00"),
--     get_texture_info("texture_hud_char_0"),
--     get_texture_info("texture_hud_char_1"),
--     get_texture_info("texture_hud_char_2"),
--     get_texture_info("texture_hud_char_3"),
--     get_texture_info("texture_hud_char_4"),
--     get_texture_info("texture_hud_char_5"),
--     get_texture_info("texture_hud_char_6"),
--     get_texture_info("texture_hud_char_7"),
--     get_texture_info("texture_hud_char_8"),
--     get_texture_info("texture_hud_char_9"),
--     get_texture_info("texture_hud_char_A"),
--     get_texture_info("texture_hud_char_B"),
--     get_texture_info("texture_hud_char_C"),
--     get_texture_info("texture_hud_char_D"),
--     get_texture_info("texture_hud_char_E"),
--     get_texture_info("texture_hud_char_F"),
--     get_texture_info("texture_hud_char_G"),
--     get_texture_info("texture_hud_char_H"),
--     get_texture_info("texture_hud_char_I"),
--     get_texture_info("texture_hud_char_J"),
--     get_texture_info("texture_hud_char_K"),
--     get_texture_info("texture_hud_char_L"),
--     get_texture_info("texture_hud_char_M"),
--     get_texture_info("texture_hud_char_N"),
--     get_texture_info("texture_hud_char_O"),
--     get_texture_info("texture_hud_char_P"),
--     get_texture_info("texture_hud_char_Q"),
--     get_texture_info("texture_hud_char_R"),
--     get_texture_info("texture_hud_char_S"),
--     get_texture_info("texture_hud_char_T"),
--     get_texture_info("texture_hud_char_U"),
--     get_texture_info("texture_hud_char_V"),
--     get_texture_info("texture_hud_char_W"),
--     get_texture_info("texture_hud_char_X"),
--     get_texture_info("texture_hud_char_Y"),
--     get_texture_info("texture_hud_char_Z"),
--     get_texture_info("texture_hud_char_apostrophe"),
--     get_texture_info("texture_hud_char_double_quote"),

--     get_texture_info("texture_hud_char_exclamation"),
--     get_texture_info("texture_hud_char_hashtag"),
--     get_texture_info("texture_hud_char_question"),
--     get_texture_info("texture_hud_char_ampersand"),
--     get_texture_info("texture_hud_char_percent"),
--     get_texture_info("texture_hud_char_slash"),
--     get_texture_info("texture_hud_char_multiply"),
--     get_texture_info("texture_hud_char_coin"),
--     get_texture_info("texture_hud_char_mario_head"),
--     get_texture_info("texture_hud_char_luigi_head"),
--     get_texture_info("texture_hud_char_toad_head"),
--     get_texture_info("texture_hud_char_waluigi_head"),
--     get_texture_info("texture_hud_char_wario_head"),
--     get_texture_info("texture_hud_char_star"),
--     get_texture_info("texture_hud_char_period"),
--     get_texture_info("texture_hud_char_key"),
--     get_texture_info("texture_hud_char_comma"),
--     get_texture_info("texture_hud_char_dash"),
--     get_texture_info("texture_hud_char_divide"),
--     get_texture_info("texture_hud_char_period"),
--     get_texture_info("texture_hud_char_plus"),
--     get_texture_info("texture_credits_char_3"),
--     get_texture_info("texture_credits_char_4"),
--     get_texture_info("texture_credits_char_6"),
--     get_texture_info("texture_credits_char_A"),
--     get_texture_info("texture_credits_char_B"),
--     get_texture_info("texture_credits_char_C"),
--     get_texture_info("texture_credits_char_D"),
--     get_texture_info("texture_credits_char_E"),
--     get_texture_info("texture_credits_char_F"),
--     get_texture_info("texture_credits_char_G"),
--     get_texture_info("texture_credits_char_H"),
--     get_texture_info("texture_credits_char_I"),
--     get_texture_info("texture_credits_char_J"),
--     get_texture_info("texture_credits_char_K"),
--     get_texture_info("texture_credits_char_L"),
--     get_texture_info("texture_credits_char_M"),
--     get_texture_info("texture_credits_char_N"),
--     get_texture_info("texture_credits_char_O"),
--     get_texture_info("texture_credits_char_P"),
--     get_texture_info("texture_credits_char_Q"),
--     get_texture_info("texture_credits_char_R"),
--     get_texture_info("texture_credits_char_S"),
--     get_texture_info("texture_credits_char_T"),
--     get_texture_info("texture_credits_char_U"),
--     get_texture_info("texture_credits_char_V"),
--     get_texture_info("texture_credits_char_W"),
--     get_texture_info("texture_credits_char_X"),
--     get_texture_info("texture_credits_char_Y"),
--     get_texture_info("texture_credits_char_Z"),
--     get_texture_info("texture_credits_char_period"),
--     get_texture_info("texture_hud_char_camera"),
--     get_texture_info("texture_hud_char_lakitu"),
--     get_texture_info("texture_hud_char_no_camera"),
--     get_texture_info("texture_hud_char_arrow_up"),
--     get_texture_info("texture_hud_char_arrow_down"),
--     get_texture_info("texture_shadow_quarter_circle"),
--     get_texture_info("texture_shadow_quarter_square"),
--     get_texture_info("texture_shadow_spike_ext"),
--     get_texture_info("texture_transition_star_half"),
--     get_texture_info("texture_transition_circle_half"),
--     get_texture_info("texture_transition_mario"),
--     get_texture_info("texture_transition_bowser_half"),
--     get_texture_info("texture_waterbox_water"),
--     get_texture_info("texture_waterbox_jrb_water"),
--     get_texture_info("texture_waterbox_unknown_water"),
--     get_texture_info("texture_waterbox_mist"),
--     get_texture_info("texture_waterbox_lava"),
--     get_texture_info("texture_ia8_up_arrow"),
--     get_texture_info("sky_09000000"),
--     get_texture_info("sky_09000800"),
--     get_texture_info("sky_09001000"),
--     get_texture_info("sky_09001800"),
--     get_texture_info("sky_09002000"),
--     get_texture_info("sky_09003000"),
--     get_texture_info("sky_09003800"),
--     get_texture_info("sky_09004800"),
--     get_texture_info("sky_09005000"),
--     get_texture_info("sky_09005800"),
--     get_texture_info("sky_09006000"),
--     get_texture_info("texture_metal_hole"),
--     get_texture_info("sky_09007000"),
--     get_texture_info("sky_09007800"),
--     get_texture_info("sky_09008000"),
--     get_texture_info("snow_09000000"),
--     get_texture_info("snow_09000800"),
--     get_texture_info("snow_09001000"),
--     get_texture_info("snow_09002000"),
--     get_texture_info("snow_09002800"),
--     get_texture_info("snow_09003000"),
--     get_texture_info("snow_09003800"),
--     get_texture_info("snow_09004000"),
--     get_texture_info("snow_09004800"),
--     get_texture_info("snow_09005000"),
--     get_texture_info("snow_09005800"),
--     get_texture_info("snow_09006000"),
--     get_texture_info("snow_09006800"),
--     get_texture_info("snow_09007000"),
--     get_texture_info("snow_09008000"),
--     get_texture_info("snow_09008800"),
--     get_texture_info("snow_09009000"),
--     get_texture_info("snow_09009800"),
--     get_texture_info("spooky_09000000"),
--     get_texture_info("spooky_09000800"),
--     get_texture_info("spooky_09001800"),
--     get_texture_info("spooky_09002800"),
--     get_texture_info("spooky_09003800"),
--     get_texture_info("spooky_09004800"),
--     get_texture_info("spooky_09005000"),
--     get_texture_info("spooky_09006000"),
--     get_texture_info("spooky_09006800"),
--     get_texture_info("spooky_09007000"),
--     get_texture_info("spooky_09008000"),
--     get_texture_info("spooky_09008800"),
--     get_texture_info("spooky_09009000"),
--     get_texture_info("spooky_0900A000"),
--     get_texture_info("spooky_0900A800"),
--     get_texture_info("spooky_0900B000"),
--     get_texture_info("spooky_0900B800"),
--     get_texture_info("title_texture_0A0001C0"),
--     get_texture_info("title_texture_0A000E40"),
--     get_texture_info("title_texture_0A001AC0"),
--     get_texture_info("title_texture_0A002740"),
--     get_texture_info("title_texture_0A0033C0"),
--     get_texture_info("title_texture_0A004040"),
--     get_texture_info("title_texture_0A004CC0"),
--     get_texture_info("title_texture_0A005940"),
--     get_texture_info("water_09000000"),
--     get_texture_info("water_09000800"),
--     get_texture_info("water_09001800"),
--     get_texture_info("water_09002800"),
--     get_texture_info("water_09003800"),
--     get_texture_info("water_09004800"),
--     get_texture_info("water_09005800"),
--     get_texture_info("water_09006000"),
--     get_texture_info("water_09006800"),
--     get_texture_info("water_09007800"),
--     get_texture_info("water_09008800"),
--     get_texture_info("water_09009000"),
--     get_texture_info("water_0900A000"),
--     get_texture_info("water_0900A800"),
--     get_texture_info("water_0900B800"),
--     get_texture_info("bbh_seg7_texture_07000000"),
--     get_texture_info("bbh_seg7_texture_07001000"),
--     get_texture_info("bbh_seg7_texture_07001800"),
--     get_texture_info("bbh_seg7_texture_07002000"),
--     get_texture_info("bbh_seg7_texture_07003000"),
--     get_texture_info("bbh_seg7_texture_07003400"),
--     get_texture_info("bbh_seg7_texture_07004400"),
--     get_texture_info("bitdw_seg7_texture_07000000"),
--     get_texture_info("bitdw_seg7_texture_07000800"),
--     get_texture_info("bitdw_seg7_texture_07001000"),
--     get_texture_info("bitdw_seg7_texture_07001800"),
--     get_texture_info("bitfs_seg7_texture_07000000"),
--     get_texture_info("bitfs_seg7_texture_07001000"),
--     get_texture_info("bitfs_seg7_texture_07001800"),
--     get_texture_info("bits_seg7_texture_07000000"),
--     get_texture_info("bits_seg7_texture_07001000"),
--     get_texture_info("bits_seg7_texture_07002000"),
--     get_texture_info("bob_seg7_texture_07000000"),
--     get_texture_info("bob_seg7_texture_07000800"),
--     get_texture_info("bob_seg7_texture_07001000"),
--     get_texture_info("bob_seg7_texture_07001800"),
--     get_texture_info("bob_seg7_texture_07002000"),
--     get_texture_info("bowser_1_seg7_texture_07000000"),
--     get_texture_info("bowser_1_seg7_texture_07001000"),
--     get_texture_info("bowser_1_seg7_texture_07001800"),
--     get_texture_info("bowser_2_seg7_texture_07000000"),
--     get_texture_info("bowser_3_seg7_texture_07000000"),
--     get_texture_info("bowser_3_seg7_texture_07000800"),
--     get_texture_info("bowser_3_seg7_texture_07001000"),
--     get_texture_info("castle_grounds_seg7_texture_0700C9E8"),
--     get_texture_info("castle_grounds_seg7_texture_0700D9E8"),
--     get_texture_info("castle_grounds_seg7_texture_07000000"),
--     get_texture_info("castle_grounds_seg7_texture_07001000"),
--     get_texture_info("castle_grounds_seg7_texture_07002000"),
--     get_texture_info("texture_castle_light"),
--     get_texture_info("inside_castle_seg7_texture_07000800"),
--     get_texture_info("inside_castle_seg7_texture_07001000"),
--     get_texture_info("inside_castle_seg7_texture_07002000"),
--     get_texture_info("inside_castle_seg7_texture_07003000"),
--     get_texture_info("inside_castle_seg7_texture_07003800"),
--     get_texture_info("inside_castle_seg7_texture_07004800"),
--     get_texture_info("inside_castle_seg7_texture_07005800"),
--     get_texture_info("inside_castle_seg7_texture_07006000"),
--     get_texture_info("inside_castle_seg7_texture_07006800"),
--     get_texture_info("inside_castle_seg7_texture_07007000"),
--     get_texture_info("inside_castle_seg7_texture_07007800"),
--     get_texture_info("inside_castle_seg7_texture_07008000"),
--     get_texture_info("inside_castle_seg7_texture_07008800"),
--     get_texture_info("inside_castle_seg7_texture_07009000"),
--     get_texture_info("inside_castle_seg7_texture_07009800"),
--     get_texture_info("inside_castle_seg7_texture_0700A000"),
--     get_texture_info("inside_castle_seg7_texture_0700A800"),
--     get_texture_info("inside_castle_seg7_texture_0700B800"),
--     get_texture_info("inside_castle_seg7_texture_0700C800"),
--     get_texture_info("inside_castle_seg7_texture_0700D800"),
--     get_texture_info("inside_castle_seg7_texture_0700E800"),
--     get_texture_info("inside_castle_seg7_texture_0700F800"),
--     get_texture_info("inside_castle_seg7_texture_07012800"),
--     get_texture_info("inside_castle_seg7_texture_07013800"),
--     get_texture_info("inside_castle_seg7_texture_07014800"),
--     get_texture_info("inside_castle_seg7_texture_07015800"),
--     get_texture_info("inside_castle_seg7_texture_07016800"),
--     get_texture_info("inside_castle_seg7_texture_07017000"),
--     get_texture_info("inside_castle_seg7_texture_07017800"),
--     get_texture_info("inside_castle_seg7_texture_07018800"),
--     get_texture_info("inside_castle_seg7_texture_07019800"),
--     get_texture_info("inside_castle_seg7_texture_0701A800"),
--     get_texture_info("inside_castle_seg7_texture_0701B800"),
--     get_texture_info("inside_castle_seg7_texture_0701C800"),
--     get_texture_info("inside_castle_seg7_texture_0701D800"),
--     get_texture_info("inside_castle_seg7_texture_0701E800"),
--     get_texture_info("inside_castle_seg7_texture_0701F800"),
--     get_texture_info("inside_castle_seg7_texture_07020800"),
--     get_texture_info("ccm_seg7_texture_07011958"),
--     get_texture_info("ccm_seg7_texture_07000000"),
--     get_texture_info("ccm_seg7_texture_07000800"),
--     get_texture_info("ccm_seg7_texture_07000900"),
--     get_texture_info("ccm_seg7_texture_07001100"),
--     get_texture_info("ccm_seg7_texture_07001900"),
--     get_texture_info("ccm_seg7_texture_07002100"),
--     get_texture_info("ccm_seg7_texture_07002900"),
--     get_texture_info("ccm_seg7_texture_07003100"),
--     get_texture_info("ccm_seg7_texture_07003900"),
--     get_texture_info("ccm_seg7_texture_07003B00"),
--     get_texture_info("ccm_seg7_texture_07004300"),
--     get_texture_info("ccm_seg7_texture_07004B00"),
--     get_texture_info("cotmc_seg7_texture_07000000"),
--     get_texture_info("cotmc_seg7_texture_07001000"),
--     get_texture_info("cotmc_seg7_texture_07001800"),
--     get_texture_info("cotmc_seg7_texture_07002000"),
--     get_texture_info("cotmc_seg7_texture_07002800"),
--     get_texture_info("ddd_seg7_texture_07000000"),
--     get_texture_info("ddd_seg7_texture_07001000"),
--     get_texture_info("ddd_seg7_texture_07001800"),
--     get_texture_info("ddd_seg7_texture_07002000"),
--     get_texture_info("ddd_seg7_texture_07003000"),
--     get_texture_info("hmc_seg7_texture_07024CE0"),
--     get_texture_info("hmc_seg7_texture_07000000"),
--     get_texture_info("hmc_seg7_texture_07001000"),
--     get_texture_info("hmc_seg7_texture_07002000"),
--     get_texture_info("hmc_seg7_texture_07003000"),
--     get_texture_info("hmc_seg7_texture_07003800"),
--     get_texture_info("hmc_seg7_texture_07004000"),
--     get_texture_info("hmc_seg7_texture_07004800"),
--     get_texture_info("intro_seg7_texture_07007EA0"),
--     get_texture_info("intro_seg7_texture_070086A0"),
--     get_texture_info("jrb_seg7_texture_07000000"),
--     get_texture_info("jrb_seg7_texture_07000800"),
--     get_texture_info("jrb_seg7_texture_07001800"),
--     get_texture_info("jrb_seg7_texture_07002000"),
--     get_texture_info("lll_seg7_texture_07000000"),
--     get_texture_info("lll_seg7_texture_07000800"),
--     get_texture_info("lll_seg7_texture_07001000"),
--     get_texture_info("lll_seg7_texture_07001800"),
--     get_texture_info("lll_seg7_texture_07002000"),
--     get_texture_info("lll_seg7_texture_07002800"),
--     get_texture_info("lll_seg7_texture_07003000"),
--     get_texture_info("lll_seg7_texture_07003800"),
--     get_texture_info("lll_seg7_texture_07004000"),
--     get_texture_info("lll_seg7_texture_07004800"),
--     get_texture_info("lll_seg7_texture_07005000"),
--     get_texture_info("lll_seg7_texture_07005800"),
--     get_texture_info("lll_seg7_texture_07006000"),
--     get_texture_info("lll_seg7_texture_07006800"),
--     get_texture_info("lll_seg7_texture_07007000"),
--     get_texture_info("lll_seg7_texture_07007800"),
--     get_texture_info("lll_seg7_texture_07008000"),
--     get_texture_info("lll_seg7_texture_07008800"),
--     get_texture_info("lll_seg7_texture_07009000"),
--     get_texture_info("lll_seg7_texture_07009800"),
--     get_texture_info("lll_seg7_texture_0700A000"),
--     get_texture_info("lll_seg7_texture_0700A800"),
--     get_texture_info("lll_seg7_texture_0700B000"),
--     get_texture_info("lll_seg7_texture_0700B800"),
--     get_texture_info("lll_seg7_texture_0700C000"),
--     get_texture_info("lll_seg7_texture_0700C800"),
--     get_texture_info("lll_seg7_texture_0700D000"),
--     get_texture_info("lll_seg7_texture_0700D200"),
--     get_texture_info("lll_seg7_texture_0700D400"),
--     get_texture_info("lll_seg7_texture_0700DC00"),
--     get_texture_info("lll_seg7_texture_0700E400"),
--     get_texture_info("lll_seg7_texture_0700EC00"),
--     get_texture_info("lll_seg7_texture_0700F400"),
--     get_texture_info("texture_menu_stone"),
--     get_texture_info("texture_menu_dark_stone"),
--     get_texture_info("texture_menu_mario_save"),
--     get_texture_info("texture_menu_mario_new"),
--     get_texture_info("texture_menu_erase"),
--     get_texture_info("texture_menu_copy"),
--     get_texture_info("texture_menu_file"),
--     get_texture_info("texture_menu_score"),
--     get_texture_info("texture_menu_sound"),
--     get_texture_info("texture_menu_idle_hand"),
--     get_texture_info("texture_menu_grabbing_hand"),
--     get_texture_info("texture_menu_hud_char_katakana_hu"),
--     get_texture_info("texture_menu_hud_char_katakana_small_a"),
--     get_texture_info("texture_menu_hud_char_katakana_i"),
--     get_texture_info("texture_menu_hud_char_katakana_ru"),
--     get_texture_info("texture_menu_hud_char_katakana_se"),
--     get_texture_info("texture_menu_hud_char_katakana_re"),
--     get_texture_info("texture_menu_hud_char_katakana_ku"),
--     get_texture_info("texture_menu_hud_char_katakana_to"),
--     get_texture_info("texture_menu_hud_char_hiragana_wo"),
--     get_texture_info("texture_menu_hud_char_katakana_ko"),
--     get_texture_info("texture_menu_hud_char_kana_handakuten_pi"),
--     get_texture_info("texture_menu_hud_char_choonpu"),
--     get_texture_info("texture_menu_hud_char_hiragana_su"),
--     get_texture_info("texture_menu_hud_char_hiragana_ru"),
--     get_texture_info("texture_menu_hud_char_hiragana_ke"),
--     get_texture_info("texture_menu_hud_char_katakana_ma"),
--     get_texture_info("texture_menu_hud_char_katakana_ri"),
--     get_texture_info("texture_menu_hud_char_katakana_o"),
--     get_texture_info("texture_menu_hud_char_katakana_su"),
--     get_texture_info("texture_menu_hud_char_katakana_a"),
--     get_texture_info("texture_menu_hud_char_hiragana_mi"),
--     get_texture_info("texture_menu_hud_char_hira_dakuten_do"),
--     get_texture_info("texture_menu_hud_char_hiragana_no"),
--     get_texture_info("texture_menu_hud_char_question"),
--     get_texture_info("texture_menu_hud_char_katakana_sa"),
--     get_texture_info("texture_menu_hud_char_katakana_u"),
--     get_texture_info("texture_menu_hud_char_katakana_n"),
--     get_texture_info("texture_menu_hud_char_kana_dakuten_do"),
--     get_texture_info("texture_menu_course_upper"),
--     get_texture_info("texture_menu_course_lower"),
--     get_texture_info("pss_seg7_texture_07000000"),
--     get_texture_info("pss_seg7_texture_07000800"),
--     get_texture_info("pss_seg7_texture_07001000"),
--     get_texture_info("texture_quarter_flying_carpet"),
--     get_texture_info("rr_seg7_texture_07000800"),
--     get_texture_info("rr_seg7_texture_07001800"),
--     get_texture_info("sl_seg7_texture_07000000"),
--     get_texture_info("sl_seg7_texture_07000800"),
--     get_texture_info("sl_seg7_texture_07001000"),
--     get_texture_info("sl_seg7_texture_07001800"),
--     get_texture_info("sl_seg7_texture_07002000"),
--     get_texture_info("ssl_quicksand"),
--     get_texture_info("ssl_seg7_texture_07000000"),
--     get_texture_info("ssl_seg7_texture_07000800"),
--     get_texture_info("ssl_pyramid_sand"),
--     get_texture_info("ssl_seg7_texture_07001800"),
--     get_texture_info("ssl_seg7_texture_07002000"),
--     get_texture_info("ssl_seg7_texture_07002800"),
--     get_texture_info("ssl_seg7_texture_07003800"),
--     get_texture_info("ssl_seg7_texture_0700BFA8"),
--     get_texture_info("ssl_seg7_texture_0700C7A8"),
--     get_texture_info("ssl_seg7_texture_0700D7A8"),
--     get_texture_info("ssl_seg7_texture_0700E7A8"),
--     get_texture_info("thi_seg7_texture_07000000"),
--     get_texture_info("thi_seg7_texture_07000800"),
--     get_texture_info("totwc_seg7_texture_07000000"),
--     get_texture_info("totwc_seg7_texture_07001000"),
--     get_texture_info("totwc_seg7_texture_07001800"),
--     get_texture_info("totwc_seg7_texture_07002000"),
--     get_texture_info("ttc_yellow_triangle"),
--     get_texture_info("ttc_seg7_texture_07000000"),
--     get_texture_info("ttc_seg7_texture_07000800"),
--     get_texture_info("ttm_seg7_texture_0702AD30"),
--     get_texture_info("ttm_seg7_texture_07000000"),
--     get_texture_info("ttm_seg7_texture_07000800"),
--     get_texture_info("ttm_seg7_texture_07001000"),
--     get_texture_info("ttm_seg7_texture_07001800"),
--     get_texture_info("ttm_seg7_texture_07002000"),
--     get_texture_info("ttm_seg7_texture_07002800"),
--     get_texture_info("ttm_seg7_texture_07003000"),
--     get_texture_info("ttm_seg7_texture_07004000"),
--     get_texture_info("vcutm_seg7_texture_07000000"),
--     get_texture_info("vcutm_seg7_texture_07000800"),
--     get_texture_info("vcutm_seg7_texture_07001800"),
--     get_texture_info("vcutm_seg7_texture_07002800"),
--     get_texture_info("wdw_seg7_texture_07000000"),
--     get_texture_info("wdw_seg7_texture_07000800"),
--     get_texture_info("wdw_seg7_texture_07001000"),
--     get_texture_info("wdw_seg7_texture_07001800"),
--     get_texture_info("wdw_seg7_texture_07002000"),
--     get_texture_info("wf_seg7_texture_07000000"),
--     get_texture_info("wf_seg7_texture_07000800"),
--     get_texture_info("wf_seg7_texture_07001000"),
--     get_texture_info("wf_seg7_texture_07001800"),
--     get_texture_info("wf_seg7_texture_07002000"),
--     get_texture_info("wf_seg7_texture_07002800"),
--     get_texture_info("wmotr_seg7_texture_07000000"),
--     get_texture_info("wmotr_seg7_texture_07000800"),
--     get_texture_info("wmotr_seg7_texture_07000C00"),
--     get_texture_info("wmotr_seg7_texture_07001400"),
--     get_texture_info("wmotr_seg7_texture_07001600"),
--     get_texture_info("mario_texture_metal_shade"),
--     get_texture_info("mario_texture_metal_light"),
--     get_texture_info("mario_texture_yellow_button"),
--     get_texture_info("mario_texture_m_logo"),
--     get_texture_info("mario_texture_m_blend"),
--     get_texture_info("mario_texture_m_cap"),
--     get_texture_info("mario_texture_hair_sideburn"),
--     get_texture_info("mario_texture_add_sideburn"),
--     get_texture_info("mario_texture_skin_sideburn"),
--     get_texture_info("mario_texture_mustache"),
--     get_texture_info("mario_texture_eyes_front"),
--     get_texture_info("mario_texture_eyes_half_closed"),
--     get_texture_info("mario_texture_eyes_closed"),
--     get_texture_info("mario_texture_eyes_right"),
--     get_texture_info("mario_texture_eyes_left"),
--     get_texture_info("mario_texture_eyes_up"),
--     get_texture_info("mario_texture_eyes_down"),
--     get_texture_info("mario_texture_eyes_dead"),
--     get_texture_info("mario_texture_wings_half_1"),
--     get_texture_info("mario_texture_wings_half_2"),
--     get_texture_info("mario_texture_metal_wings_half_1_shade"),
--     get_texture_info("mario_texture_metal_wings_half_1_light"),
--     get_texture_info("mario_texture_metal_wings_half_2_shade"),
--     get_texture_info("mario_texture_metal_wings_half_2_light"),
--     get_texture_info("mario_cap_seg3_texture_0301CF50"),
--     get_texture_info("mario_cap_seg3_texture_0301DF50"),
--     get_texture_info("mario_cap_seg3_texture_0301E750"),
--     get_texture_info("mario_cap_seg3_texture_0301F750"),
--     get_texture_info("mario_cap_seg3_texture_03020750"),
--     get_texture_info("mario_cap_seg3_texture_03021750"),
--     get_texture_info("impact_smoke_seg6_texture_0605AA28"),
--     get_texture_info("impact_smoke_seg6_texture_0605CA28"),
--     get_texture_info("impact_smoke_seg6_texture_0605EA28"),
--     get_texture_info("impact_smoke_seg6_texture_06060A28"),
--     get_texture_info("luigi_texture_l_logo"),
--     get_texture_info("luigi_texture_l_blend"),
--     get_texture_info("luigi_texture_l_cap"),
--     get_texture_info("luigi_texture_hair_sideburn"),
--     get_texture_info("luigi_texture_add_sideburn"),
--     get_texture_info("luigi_texture_skin_sideburn"),
--     get_texture_info("luigi_texture_mustache"),
--     get_texture_info("toad_player_texture_cap"),
--     get_texture_info("toad_player_texture_spots"),
--     get_texture_info("toad_player_texture_hair"),
--     get_texture_info("toad_player_texture_face_neutral"),
--     get_texture_info("toad_player_texture_face_dead"),
--     get_texture_info("toad_player_texture_eyes_front"),
--     get_texture_info("toad_player_texture_eyes_half_closed"),
--     get_texture_info("toad_player_texture_eyes_closed"),
--     get_texture_info("toad_player_texture_eyes_right"),
--     get_texture_info("toad_player_texture_eyes_left"),
--     get_texture_info("toad_player_texture_eyes_up"),
--     get_texture_info("toad_player_texture_eyes_down"),
--     get_texture_info("toad_player_texture_eyes_dead"),
--     get_texture_info("wario_texture_white_button"),
--     get_texture_info("wario_texture_w_logo"),
--     get_texture_info("wario_texture_w_blend"),
--     get_texture_info("wario_texture_w_cap"),
--     get_texture_info("wario_texture_hair_sideburn"),
--     get_texture_info("wario_texture_add_sideburn"),
--     get_texture_info("wario_texture_skin_sideburn"),
--     get_texture_info("wario_texture_mouth"),
--     get_texture_info("wario_texture_mouth_dead"),
--     get_texture_info("wario_texture_eyes_front"),
--     get_texture_info("wario_texture_eyes_half_closed"),
--     get_texture_info("wario_texture_eyes_closed"),
--     get_texture_info("wario_texture_eyes_right"),
--     get_texture_info("wario_texture_eyes_left"),
--     get_texture_info("wario_texture_eyes_up"),
--     get_texture_info("wario_texture_eyes_down"),
--     get_texture_info("wario_texture_eyes_dead"),
--     get_texture_info("waluigi_texture_r_logo"),
--     get_texture_info("waluigi_texture_r_blend"),
--     get_texture_info("waluigi_texture_r_cap"),
--     get_texture_info("waluigi_texture_hair_sideburn"),
--     get_texture_info("waluigi_texture_add_sideburn"),
--     get_texture_info("waluigi_texture_skin_sideburn"),
--     get_texture_info("waluigi_texture_mouth"),
--     get_texture_info("waluigi_texture_mouth_dead"),
--     get_texture_info("waluigi_texture_eyes_front"),
--     get_texture_info("waluigi_texture_eyes_half_closed"),
--     get_texture_info("waluigi_texture_eyes_closed"),
--     get_texture_info("waluigi_texture_eyes_right"),
--     get_texture_info("waluigi_texture_eyes_left"),
--     get_texture_info("waluigi_texture_eyes_up"),
--     get_texture_info("waluigi_texture_eyes_down"),
--     get_texture_info("waluigi_texture_eyes_dead"),
--     get_texture_info("texture_font_normal"),
--     get_texture_info("texture_font_aliased"),
--     get_texture_info("texture_font_title"),
--     get_texture_info("texture_font_hud"),
--     get_texture_info("texture_font_hud_recolor"),
--     get_texture_info("texture_font_special"),
--     get_texture_info("texture_font_jp"),
--     get_texture_info("texture_font_jp_aliased"),
--     get_texture_info("texture_selectionbox_back_icon"),
--     get_texture_info("texture_selectionbox_forward_icon"),
--     get_texture_info("texture_coopdx_logo"),
--     get_texture_info("gd_texture_hand_open"),
--     get_texture_info("gd_texture_hand_closed"),
--     get_texture_info("gd_texture_red_star_0"),
--     get_texture_info("gd_texture_red_star_1"),
--     get_texture_info("gd_texture_red_star_2"),
--     get_texture_info("gd_texture_red_star_3"),
--     get_texture_info("gd_texture_red_star_4"),
--     get_texture_info("gd_texture_red_star_5"),
--     get_texture_info("gd_texture_red_star_6"),
--     get_texture_info("gd_texture_red_star_7"),
--     get_texture_info("gd_texture_white_star_0"),
--     get_texture_info("gd_texture_white_star_1"),
--     get_texture_info("gd_texture_white_star_2"),
--     get_texture_info("gd_texture_white_star_3"),
--     get_texture_info("gd_texture_white_star_4"),
--     get_texture_info("gd_texture_white_star_5"),
--     get_texture_info("gd_texture_white_star_6"),
--     get_texture_info("gd_texture_white_star_7"),
--     get_texture_info("gd_texture_sparkle_0"),
--     get_texture_info("gd_texture_sparkle_1"),
--     get_texture_info("gd_texture_sparkle_2"),
--     get_texture_info("gd_texture_sparkle_3"),
--     get_texture_info("gd_texture_sparkle_4"),
--     get_texture_info("gd_texture_sparkle_5"),
-- }
-- local timer = -1
-- local curTex
-- local stopped
-- hook_event(HOOK_ON_HUD_RENDER, function ()
--     if gMarioStates[0].controller.buttonDown & Z_TRIG ~= 0 then
--         stopped = 1
--     end
--     if gMarioStates[0].controller.buttonPressed & Z_TRIG ~= 0 then
--         timer = timer - 1
--     end
--     if not stopped then
--         timer = timer + 1
--         -- local newTex = textures[((get_global_timer()) % #textures)+1]
--         local newTex = textures[(timer % #textures) + 1]
--         if curTex ~= newTex then
--             -- set_window_icon(newTex)
--             -- curTex = newTex
--         end
--     end

--     djui_hud_set_resolution(RESOLUTION_N64)
--     djui_hud_set_font(FONT_NORMAL)

--     local x = djui_hud_get_screen_width() / 2 - 100
--     local y = 0

--     djui_hud_print_text("Cycles: "..(timer // #textures), x, y, .5)
--     y = y + 10
--     for i = 0, 20 do
--         local tex = textures[((timer - i) % #textures) + 1]
--         -- djui_chat_message_create(""..(((timer - i) % #textures) + 1))
--         if tex and (timer - i) > 0 then
--             -- djui_hud_render_texture(tex, x, y, .5, .5)
--             djui_hud_print_text(""..(timer - i), x - djui_hud_measure_text(""..(timer - i)), y, .5)
--         end
--         y = y + 10
--     end
-- end)
-- set_window_title("Jogo")

